### ISSUE TITLE
セルにフラグを立てた後そのセル周囲8マスを左クリックすると、他のマスが開きます。

### ISSUE THREAD

**Issue by kei9s** [ksugimori/vue-minesweeper#55]
(1)セルにフラグを立てて(画像の1)、その周囲8マスのどこかのマスをクリックします。(画像の2)
![pic1](https://user-images.githubusercontent.com/73397995/111865656-a2486b00-89ab-11eb-8fb4-fbae2b0e2a09.png)

(2)すると、クリックしたマスでないマスが開きます。(画像の3)
![pic2](https://user-images.githubusercontent.com/73397995/111865875-ef790c80-89ac-11eb-9390-3f3246295a70.png)

**Comment by ksugimori** [comment]
報告ありがとうございます。

わかりにくいかもしれませんが、これは「仕様」です。

数字セルを左クリックしたとき `周囲８セルのフラグの数` = `クリックしたセルの数字` であれば、周囲８セルの中でフラグが立っていないセルをすべて開きます。ひとつずつクリックして開く手間を省くための仕様です。

ただし、自動的に開かれたセルの中に地雷が存在すればゲームオーバーになります。
「地雷が埋まっていないセルに間違ってフラグを立てた」というミスになるからです。

**Comment by kei9s** [comment]
丁寧な解説をありがとうございます。そういった仕様だと分からず報告してしまい失礼いたしました。
当初はバグと勘違いしてしまいましたがアプリの機能だと分かりましたので、クローズさせていただきます。
